const WORK_ORDER_STATUS = {
  REQUESTED: "REQUESTED",
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  DONE: "DONE",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

module.exports = { WORK_ORDER_STATUS };

